#! /usr/bin/env node

const check = require('./index.js')

const status = check()
if (status.name) {
  console.error('npm install needed:', status.name, 'is', status.installed, 'but should be', status.needed)
  process.exit(1)
}
